{
 "title": "SolarEdge Monitoring",
 "time": { "from": "now/w", "to": "now/w" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CurrentPower\nFROM Overview"
    }
   ]
  },
  {
   "title": "Energy today",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Production\nFROM EnergyDetails\nWHERE\n  time = CURDATE()"
    }
   ]
  },
  {
   "title": "Energy this month",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  LastMonthData\nFROM Overview"
    }
   ]
  },
  {
   "title": "Energy this year",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  LastYearData\nFROM Overview"
    }
   ]
  },
  {
   "title": "Production",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(SelfConsumption) AS \"Self Consumption\",\n  sum(Production) AS \"Export\"\nFROM (SELECT * FROM EnergyDetails WHERE $__timeFilter(time)) x"
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(SelfConsumption) AS \"Self Consumption\",\n  sum(Consumption) AS \"Import\"\nFROM (SELECT * FROM EnergyDetails WHERE $__timeFilter(time)) x\n"
    }
   ]
  },
  {
   "title": "Comparative Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  SUM(Consumption) AS \"Consumption\",\n  SUM(Production) AS \"Production\",\n  SUM(SelfConsumption) AS \"SelfConsumption\"\nFROM EnergyDetails\nWHERE\n  $__timeFilter(time)\nGROUP BY time\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Overall statistics",
   "type": "piechart",
   "description": "Statistics for selected time range",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(Consumption) AS \"Consumption\",\n  sum(Production) AS \"Production\"\nFROM (SELECT * FROM EnergyDetails WHERE $__timeFilter(time)) x"
    }
   ]
  }
 ]
}